### ISSUE TITLE
fails to build with gpgme >= 2.0.0

### ISSUE THREAD

**Issue by andreasstieger** [php-gnupg/php-gnupg#59]
php-gnupg fails to build with gpgme >= 2.0.0. 

From https://build.opensuse.org/package/live_build_log/openSUSE:Factory/php-gnupg:php8/standard/x86_64 :

````
[   12s] /home/abuild/rpmbuild/BUILD/php8-gnupg-1.5.3-build/gnupg-1.5.3/gnupg.c: In function ‘zif_gnupg_gettrustlist’:
[   12s] /home/abuild/rpmbuild/BUILD/php8-gnupg-1.5.3-build/gnupg-1.5.3/gnupg.c:1947:9: error: unknown type name ‘gpgme_trust_item_t’
[   12s]  1947 |         gpgme_trust_item_t item;
[   12s]       |         ^~~~~~~~~~~~~~~~~~
[   12s] /home/abuild/rpmbuild/BUILD/php8-gnupg-1.5.3-build/gnupg-1.5.3/gnupg.c:1963:27: error: implicit declaration of function ‘gpgme_op_trustlist_start’; did you mean ‘gpgme_op_keylist_start’? [-Wimplicit-function-declaration]
[   12s]  1963 |         if (!PHP_GNUPG_DO(gpgme_op_trustlist_start(PHPC_THIS->ctx, pattern, 0))) {
[   12s]       |                           ^~~~~~~~~~~~~~~~~~~~~~~~
````

(cut for brevity)

From the [gpgme 2.0.0 NEWS](https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gpgme.git;a=blob;f=NEWS;h=cd0e093bf83fe47b6773fb478fced07d8409fbe0;hb=gpgme-2.0.0#l31):

>  * Removed the entire trustlist feature which worked anyway only for a
>    short period in 2003.  [T4834]
