### PR TITLE
fix build with old libgpgme 1.3

### PR DESCRIPTION
**Pull request by remicollet**
At least on RHEL 7 which provides gpgme version 1.3.2

Build time:

`
/builddir/build/BUILD/php-pecl-gnupg-1.5.0~RC1/NTS/gnupg.c: In function 'php_gnupg_this_make':
/builddir/build/BUILD/php-pecl-gnupg-1.5.0~RC1/NTS/gnupg.c:173:3: warning: implicit declaration of function 'gpgme_set_pinentry_mode' [-Wimplicit-function-declaration]
   gpgme_set_pinentry_mode(ctx, GPGME_PINENTRY_MODE_LOOPBACK);
   ^
/builddir/build/BUILD/php-pecl-gnupg-1.5.0~RC1/NTS/gnupg.c:173:32: error: 'GPGME_PINENTRY_MODE_LOOPBACK' undeclared (first use in this function)
   gpgme_set_pinentry_mode(ctx, GPGME_PINENTRY_MODE_LOOPBACK);
                                ^
/builddir/build/BUILD/php-pecl-gnupg-1.5.0~RC1/NTS/gnupg.c:173:32: note: each undeclared identifier is reported only once for each function it appears in
/builddir/build/BUILD/php-pecl-gnupg-1.5.0~RC1/NTS/gnupg.c: In function 'zif_gnupg_keyinfo':
/builddir/build/BUILD/php-pecl-gnupg-1.5.0~RC1/NTS/gnupg.c:1126:20: error: 'struct _gpgme_subkey' has no member named 'curve'
    if (gpgme_subkey->curve) {
                    ^
In file included from /usr/include/php/main/php.h:38:0,
                 from /builddir/build/BUILD/php-pecl-gnupg-1.5.0~RC1/NTS/gnupg.c:21:
/builddir/build/BUILD/php-pecl-gnupg-1.5.0~RC1/NTS/gnupg.c:521:54: error: 'struct _gpgme_subkey' has no member named 'curve'
   PHPC_VAL_CAST_TO_PZVAL(_g_arr), #_g_name, _g_struct->_g_key)
                                                      ^
/usr/include/php/Zend/zend_API.h:388:111: note: in definition of macro 'add_assoc_string'
 #define add_assoc_string(__arg, __key, __str, __duplicate) add_assoc_string_ex(__arg, __key, strlen(__key)+1, __str, __duplicate)
                                                                                                               ^
/builddir/build/BUILD/php-pecl-gnupg-1.5.0~RC1/NTS/gnupg.c:520:2: note: in expansion of macro 'PHPC_ARRAY_ADD_ASSOC_CSTR'
  PHPC_ARRAY_ADD_ASSOC_CSTR(\
  ^
/builddir/build/BUILD/php-pecl-gnupg-1.5.0~RC1/NTS/gnupg.c:523:2: note: in expansion of macro 'PHP_GNUPG_ARRAY_ADD_ASSOC_CSTR_EX'
  PHP_GNUPG_ARRAY_ADD_ASSOC_CSTR_EX(_g_arr, _g_name, _g_struct, _g_name)
  ^
/builddir/build/BUILD/php-pecl-gnupg-1.5.0~RC1/NTS/gnupg.c:1127:5: note: in expansion of macro 'PHP_GNUPG_ARRAY_ADD_ASSOC_CSTR'
     PHP_GNUPG_ARRAY_ADD_ASSOC_CSTR(subkey, curve, gpgme_subkey);
     ^
/builddir/build/BUILD/php-pecl-gnupg-1.5.0~RC1/NTS/gnupg.c: In function 'zif_gnupg_encrypt':
/builddir/build/BUILD/php-pecl-gnupg-1.5.0~RC1/NTS/gnupg.c:505:48: warning: operation on '_phpc_this->err' may be undefined [-Wsequence-point]
 #define PHP_GNUPG_DO(_action) ((PHPC_THIS->err = _action) == GPG_ERR_NO_ERROR)
                                                ^
/builddir/build/BUILD/php-pecl-gnupg-1.5.0~RC1/NTS/gnupg.c:1445:7: note: in expansion of macro 'PHP_GNUPG_DO'
  if (!PHP_GNUPG_DO(PHPC_THIS->err = gpgme_data_new(&out))) {
       ^
`

### CODE REVIEW

**Comment by remicollet** [comment]
I have reverted the library check and fix some condition.

Notice, GPGME_VERSION_NUMBER was introduced in 1.4.0, so checking for lower value is broken.

On RHEL-7

```
# php -n -d extension=modules/gnupg.so --ri gnupg

gnupg

gnupg support => enabled
GPGme Version => 1.3.2
Extension Version => 1.5.0RC1

```

And

```
TEST RESULT SUMMARY
---------------------------------------------------------------------
Exts skipped    :    0
Exts tested     :   29
---------------------------------------------------------------------

Number of tests :   34                34
Tests skipped   :    0 (  0.0%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    0 (  0.0%) (  0.0%)
Expected fail   :    0 (  0.0%) (  0.0%)
Tests passed    :   34 (100.0%) (100.0%)
---------------------------------------------------------------------
Time taken      :   32 seconds
=====================================================================

```

Of course, using gnupg version 1

With this change, minimal supported version is probably 1.3.0 which is from 2010

**Comment by bukka** [comment]
I think it makes sense to set min to 1.3.0. Just thinking if it would also make sense to add build check for that to config.m4.

**Comment by remicollet** [comment]
> I think it makes sense to set min to 1.3.0. Just thinking if it would also make sense to add a build check for that to config.m4.

Indeed, see last commit (kind of hack... bur simple ;)
